# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=25)),
                ('seller_address', models.CharField(max_length=25)),
                ('seller_email', models.CharField(max_length=25)),
                ('seller_phone', models.CharField(max_length=10)),
            ],
        ),
    ]
