# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesManagement', '0003_custom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='role',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
