# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesManagement', '0004_auto_20160702_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='address',
            field=models.CharField(default='India', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalesManagement.Custom_User'),
        ),
    ]
