# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesManagement', '0005_auto_20160702_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalesManagement.Seller'),
        ),
    ]
