# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesManagement', '0006_auto_20160703_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_password',
            field=models.CharField(default='password', max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_password',
            field=models.CharField(default='password', max_length=20),
        ),
    ]
